### ISSUE TITLE
(Reshetnikov, Polyntsev, Poletaev) about (Kozlov_Shkirkov_Galkin)

### ISSUE THREAD

**Issue by PetrPoletaev** [SergeyStaroletov/Verify17#27]
Некорректное отображение исходного текста из txt-файла.
![2017-02-09_22-33-50](https://cloud.githubusercontent.com/assets/22346628/22790993/86f8d6d0-ef1a-11e6-9282-b7f06f1ec50b.png)

**Comment by betanets** [comment]
Дубликат с #8
