### ISSUE TITLE
(Reshetnikov, Polyntsev, Poletaev) about (Kozlov_Shkirkov_Galkin) 

### ISSUE THREAD

**Issue by Polincevsergey** [SergeyStaroletov/Verify17#52]
Открыл файл с тектом:
![default](https://cloud.githubusercontent.com/assets/22850161/22853550/e7fa21ec-f08b-11e6-9790-94e65162457f.png)
а где русские буквы?
в файла та все таки русские буквы:
![default](https://cloud.githubusercontent.com/assets/22850161/22853551/f8351d32-f08b-11e6-8224-386764481bbe.png)

**Comment by betanets** [comment]
И снова дубликат с #8
Хоть смотрите прошлое-то
