### ISSUE TITLE
(Reshetnikov, Polyntsev, Poletaev) about (Kozlov_Shkirkov_Galkin)

### ISSUE THREAD

**Issue by Polincevsergey** [SergeyStaroletov/Verify17#53]
Скопировал файл CourseProject.exe другую папку и запустил.
А что ничего не запустилось? где все та? хоть бы ексепшен вылетел, я бы все понял тогда!
В описании не написано про то, что нужны другие файлы для запуска!

**Comment by rightjelkin** [comment]
В 1м пункте спецификации по сути написано, что для запуска нужны все файлы

**Comment by betanets** [comment]
![default](https://cloud.githubusercontent.com/assets/10252565/23015038/f07490f6-f463-11e6-9156-996336bbb955.PNG)
